### ISSUE TITLE
it's possible to create video from images with transition and effect?

### ISSUE THREAD

**Issue by Hari1269** [YuAo/YUDisplacementTransition#1]

**Comment by YuAo** [comment]
Yes. It is totally possible. `AVFoundation` framework is your friend. You can create tracks representing the static images and use system provided or write custom (e.g. implement the `AVVideoCompositing` protocol) video compositor to do the transition.

Closing this issue, because the question is not directly related to this project.

**Comment by Hari1269** [comment]
Yes. I getting your point. but I really like your  transition effects(YUDisplacementTransition). And it is in imageview. how I convert your transition effects in images to video. Please help me.

**Comment by Hari1269** [comment]
Yes. I getting your point. but I really like your  transition effects(YUDisplacementTransition). And it is in UIImageview. how I convert your transition effects in images to video. Please help me.

**Comment by YuAo** [comment]
The transition is not limited in UIImageViews, it works with `MTIImage`s. (See the `YUDisplacementTransition` class)

You can create a `MTIImage` from a core video image buffer (CVPixelBuffer). You can also render a `MTIImage` to a CVPixelBuffer (using a `MTIContext`). So it can play well with the AVFoundation framework and the `AVVideoCompositing` protocol.

See [MetalPetal](https://github.com/MetalPetal/MetalPetal/) for more information about `MTIImage` and `MTIContext`.

**Comment by Hari1269** [comment]
Ok, I'll try this thinks.. thanks for giving me help

**Comment by Hari1269** [comment]
Ok, I'll try this thinks.. thanks for giving me help..:)
